#!/usr/bin/python3

import os
import sys

pyfile = os.environ.get('PYFILE')
if not pyfile:
    print("Error: Environment variable $PYFILE is not set.")
    sys.exit(1)

if not os.path.isfile(pyfile):
    print(f"Error: Python script file \"{pyfile}\" not found.")
    sys.exit(1)

exec(open(pyfile).read())
