#!/bin/bash
if [ -z "$PYCODE" ]; then
	echo "Error: Environment variable \$PYCODE is not set."
	exit 1
fi

tmpfile=$(mktemp)
echo "$PYCODE" > "$tmpfile"

pycodestyle --max-line-length=80 "$tmpfile"

if [ $? -eq 0 ]; then
	python3 -c "$PYCODE"
else
	echo "Error: pycodestyle checks failed. Please fix the style issues."
fi

rm -f "$tmpfile"
